[package]
name = "gridbot"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = { version = "0.7", features = ["device"] }
cortex-m-rtic = "1.0"
panic-halt = "0.2"
stm32f7 = { version = "0.14", features = ["stm32f7x7", "rt"] }
stm32f7xx-hal = { git = "https://github.com/stm32-rs/stm32f7xx-hal", rev = "7099b07", features = ["stm32f767", "rtic"] }
