/**
 * https://github.com/Aircoookie/WLED/blob/master/tools/cdata.js
 */

const inliner = require("inliner")
const MinifyHTML = require("html-minifier-terser").minify

const fs = require("fs")

writeHtmlGzipped("INDEX", "ui/index.html", "src/ui/index.h")

function writeHtmlGzipped(key, sourceFile, resultFile) {
  console.info("Reading " + sourceFile)

  new inliner(sourceFile, function (error, html) {
    if (error) throw error

    console.info("Inlined " + html.length + " characters")

    html = MinifyHTML(html, {
     collapseWhitespace: true,
     conservativeCollapse: true,
     minifyCSS: true,
     minifyJS: true, 
     continueOnParseError: false,
     removeComments: true,
   })

    console.info("Minified to " + html.length + " characters")

    const resultContent = `/*
 * Strings for the Web UI.
 * 
 */

#include <Arduino.h>
 
// Autogenerated from ${sourceFile}, do not edit!!
const String PAGE_${key} = String("${escapeString(html)}}");
`

    console.info("Writing " + resultFile)
    fs.writeFileSync(resultFile, resultContent)
  })
}

function escapeString(str) {
  return String(str).replace(/\"/g, "\\\"")
}
